[package]
name = "testing"
version = "0.0.1"
edition = "2021"

[dependencies]
cpal = { version = "*" }
anyhow = { version = "*" }
hound = { version = "*" }
clap = { version = "*" }
structopt = { version = "*" }
ringbuf = { version = "*" }
libc = { version = "*" }